import { defineArrayMember, defineField, defineType } from "sanity";

export const homepage = defineType({
  name: "homepage",
  title: "Homepage",
  type: "document",
  groups: [
    { name: "hero", title: "Hero", default: true },
    { name: "profile", title: "Profile" },
    { name: "current", title: "Currently" },
    { name: "offScreen", title: "Off Screen" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "availabilityText",
      title: "Availability text",
      type: "string",
      group: "hero",
      description: "Short status displayed near the homepage introduction.",
      validation: (rule) => rule.required().error("Availability text is required."),
    }),
    defineField({
      name: "heroFirstName",
      title: "Hero first name",
      type: "string",
      group: "hero",
      validation: (rule) => rule.required().error("A first name is required."),
    }),
    defineField({
      name: "heroLastName",
      title: "Hero last name",
      type: "string",
      group: "hero",
      validation: (rule) => rule.required().error("A last name is required."),
    }),
    defineField({
      name: "primaryIntroduction",
      title: "Primary introduction",
      type: "text",
      rows: 3,
      group: "hero",
      validation: (rule) => rule.required().error("A primary introduction is required."),
    }),
    defineField({
      name: "secondaryIntroduction",
      title: "Secondary introduction",
      type: "text",
      rows: 3,
      group: "hero",
      validation: (rule) => rule.required().error("A secondary introduction is required."),
    }),
    defineField({
      name: "locationLabel",
      title: "Location label",
      type: "string",
      group: "hero",
      description: "Location shown alongside the local-time block.",
      validation: (rule) => rule.required().error("A location label is required."),
    }),
    defineField({
      name: "selectedProjects",
      title: "Selected projects",
      type: "array",
      group: "profile",
      description: "Choose and arrange the projects featured on the homepage.",
      of: [
        defineArrayMember({
          type: "reference",
          to: [{ type: "project" }],
          options: { disableNew: true },
        }),
      ],
      validation: (rule) => rule.unique(),
    }),
    defineField({
      name: "profileSummary",
      title: "Profile summary",
      type: "text",
      rows: 5,
      group: "profile",
      validation: (rule) => rule.required().error("A profile summary is required."),
    }),
    defineField({
      name: "profileStatistics",
      title: "Profile statistics",
      type: "array",
      group: "profile",
      of: [defineArrayMember({ type: "statistic" })],
    }),
    defineField({
      name: "currentlyBuilding",
      title: "Currently building",
      type: "string",
      group: "current",
    }),
    defineField({
      name: "currentlyLearning",
      title: "Currently learning",
      type: "string",
      group: "current",
    }),
    defineField({
      name: "currentlyExploring",
      title: "Currently exploring",
      type: "string",
      group: "current",
    }),
    defineField({
      name: "offScreenItems",
      title: "Off Screen items",
      type: "array",
      group: "offScreen",
      description: "Personal images, music or short notes shown in the Off Screen strip.",
      of: [defineArrayMember({ type: "offScreenItem" })],
    }),
    defineField({
      name: "seo",
      title: "SEO",
      type: "seo",
      group: "seo",
    }),
  ],
  preview: {
    select: { firstName: "heroFirstName", lastName: "heroLastName" },
    prepare: ({ firstName, lastName }) => ({
      title: "Homepage",
      subtitle: [firstName, lastName].filter(Boolean).join(" "),
    }),
  },
});
